<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260505182931 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE reponse_reclamation (id INT AUTO_INCREMENT NOT NULL, message LONGTEXT NOT NULL, satisfait TINYINT DEFAULT NULL, created_at DATETIME NOT NULL, reclamation_id INT NOT NULL, INDEX IDX_C7CB51012D6BA2D9 (reclamation_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE user_favorite_excursions (user_id INT NOT NULL, excursion_id INT NOT NULL, INDEX IDX_844C773AA76ED395 (user_id), INDEX IDX_844C773A4AB4296F (excursion_id), PRIMARY KEY (user_id, excursion_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE reponse_reclamation ADD CONSTRAINT FK_C7CB51012D6BA2D9 FOREIGN KEY (reclamation_id) REFERENCES reclamation (idReclamation) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_favorite_excursions ADD CONSTRAINT FK_844C773AA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser)');
        $this->addSql('ALTER TABLE user_favorite_excursions ADD CONSTRAINT FK_844C773A4AB4296F FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion)');
        $this->addSql('DROP TABLE login_history');
        $this->addSql('DROP TABLE signalement');
        $this->addSql('ALTER TABLE aeroport CHANGE latitude latitude DOUBLE PRECISION DEFAULT 0 NOT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE categorie CHANGE nom nom VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('DROP INDEX unique_nom ON categorie_hebergement');
        $this->addSql('ALTER TABLE categorie_hebergement DROP image');
        $this->addSql('ALTER TABLE commentaire CHANGE contenu contenu LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCFE6E88D7 FOREIGN KEY (idUser) REFERENCES utilisateur (idUser) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_comment_post ON commentaire');
        $this->addSql('CREATE INDEX IDX_67F068BC4B89032C ON commentaire (post_id)');
        $this->addSql('DROP INDEX fk_commentaire_utilisateur ON commentaire');
        $this->addSql('CREATE INDEX IDX_67F068BCFE6E88D7 ON commentaire (idUser)');
        $this->addSql('ALTER TABLE email_verification ADD verified TINYINT NOT NULL, CHANGE code code VARCHAR(6) NOT NULL');
        $this->addSql('ALTER TABLE excursion CHANGE description description LONGTEXT NOT NULL, CHANGE categorie_id categorie_id INT NOT NULL');
        $this->addSql('ALTER TABLE excursion ADD CONSTRAINT FK_9B08E72FBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('DROP INDEX fk_excursion_categorie ON excursion');
        $this->addSql('CREATE INDEX IDX_9B08E72FBCF5E72D ON excursion (categorie_id)');
        $this->addSql('ALTER TABLE favorite CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED94AB4296F FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_68C58ED9A76ED395 ON favorite (user_id)');
        $this->addSql('DROP INDEX fk_favorite_excursion ON favorite');
        $this->addSql('CREATE INDEX IDX_68C58ED94AB4296F ON favorite (excursion_id)');
        $this->addSql('DROP INDEX fk_hebergement_user ON hebergement');
        $this->addSql('ALTER TABLE hebergement CHANGE type type VARCHAR(50) DEFAULT NULL, CHANGE description description LONGTEXT NOT NULL, CHANGE disponibilite disponibilite VARCHAR(20) DEFAULT NULL, CHANGE nb_notes nb_notes INT DEFAULT NULL, CHANGE galleryImages galleryImages JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE hebergement ADD CONSTRAINT FK_4852DD9CB597FD62 FOREIGN KEY (idCategorie) REFERENCES categorie_hebergement (idCategorie) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_hebergement_categorie ON hebergement');
        $this->addSql('CREATE INDEX IDX_4852DD9CB597FD62 ON hebergement (idCategorie)');
        $this->addSql('ALTER TABLE notification CHANGE message message VARCHAR(255) NOT NULL, CHANGE is_read is_read TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA2D6BA2D9 FOREIGN KEY (reclamation_id) REFERENCES reclamation (idReclamation) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CA2D6BA2D9 ON notification (reclamation_id)');
        $this->addSql('ALTER TABLE paiement CHANGE reduction reduction DOUBLE PRECISION DEFAULT 0');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E5ADA84A2 FOREIGN KEY (id_reservation) REFERENCES reservation (idReservation)');
        $this->addSql('DROP INDEX fk_paiement_reservation ON paiement');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E5ADA84A2 ON paiement (id_reservation)');
        $this->addSql('ALTER TABLE post CHANGE contenu contenu LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE status status VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DF9C28DE1 FOREIGN KEY (IdUser) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('DROP INDEX fk_post_user ON post');
        $this->addSql('CREATE INDEX IDX_5A8A6C8DF9C28DE1 ON post (IdUser)');
        $this->addSql('ALTER TABLE post_like CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE post_like ADD CONSTRAINT FK_653627B84B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_like_post ON post_like');
        $this->addSql('CREATE INDEX IDX_653627B84B89032C ON post_like (post_id)');
        $this->addSql('ALTER TABLE promo_code DROP FOREIGN KEY `FK_PROMO_USER`');
        $this->addSql('ALTER TABLE promo_code DROP used, CHANGE actif actif TINYINT NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX code ON promo_code');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D8C939E77153098 ON promo_code (code)');
        $this->addSql('DROP INDEX idx_promo_user ON promo_code');
        $this->addSql('CREATE INDEX IDX_3D8C939EA76ED395 ON promo_code (user_id)');
        $this->addSql('ALTER TABLE promo_code ADD CONSTRAINT `FK_PROMO_USER` FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY `fk_question_session`');
        $this->addSql('ALTER TABLE quiz_question CHANGE question question LONGTEXT NOT NULL');
        $this->addSql('DROP INDEX fk_question_session ON quiz_question');
        $this->addSql('CREATE INDEX IDX_6033B00B613FECDF ON quiz_question (session_id)');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT `fk_question_session` FOREIGN KEY (session_id) REFERENCES quiz_session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_session DROP FOREIGN KEY `fk_quiz_user`');
        $this->addSql('ALTER TABLE quiz_session CHANGE played played TINYINT DEFAULT 0 NOT NULL, CHANGE score score INT NOT NULL');
        $this->addSql('DROP INDEX fk_quiz_user ON quiz_session');
        $this->addSql('CREATE INDEX IDX_C21E7874A76ED395 ON quiz_session (user_id)');
        $this->addSql('ALTER TABLE quiz_session ADD CONSTRAINT `fk_quiz_user` FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY `fk_rating_excursion`');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY `fk_rating_user`');
        $this->addSql('DROP INDEX unique_user_excursion ON rating');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY `fk_rating_excursion`');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D8892622A76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D88926224AB4296F FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion)');
        $this->addSql('DROP INDEX fk_rating_excursion ON rating');
        $this->addSql('CREATE INDEX IDX_D88926224AB4296F ON rating (excursion_id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT `fk_rating_excursion` FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_reclamation_user ON reclamation');
        $this->addSql('DROP INDEX idx_reclamation_reservation ON reclamation');
        $this->addSql('ALTER TABLE reclamation CHANGE description description LONGTEXT NOT NULL, CHANGE typeReclamation typeReclamation ENUM(\'TRANSPORT\',\'LOISIR\',\'HEBERGEMENT\') NOT NULL, CHANGE dateReclamation dateReclamation DATE NOT NULL, CHANGE statut statut ENUM(\'EN_ATTENTE\',\'TRAITEE\',\'REFUSEE\') NOT NULL DEFAULT \'EN_ATTENTE\', CHANGE reponseAdmin reponseAdmin LONGTEXT DEFAULT NULL, CHANGE priorite priorite ENUM(\'FAIBLE\',\'NORMAL\',\'URGENT\') DEFAULT \'NORMAL\'');
        $this->addSql('DROP INDEX idx_active ON reclamation_whatsapp_session');
        $this->addSql('DROP INDEX idx_phone ON reclamation_whatsapp_session');
        $this->addSql('ALTER TABLE reclamation_whatsapp_session CHANGE step step VARCHAR(50) NOT NULL, CHANGE reason reason LONGTEXT DEFAULT NULL, CHANGE analysis_summary analysis_summary LONGTEXT DEFAULT NULL, CHANGE turn turn INT NOT NULL, CHANGE is_active is_active TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE reclamation_whatsapp_session ADD CONSTRAINT FK_5190DD6A2D6BA2D9 FOREIGN KEY (reclamation_id) REFERENCES reclamation (idReclamation) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_reclamation ON reclamation_whatsapp_session');
        $this->addSql('CREATE INDEX IDX_5190DD6A2D6BA2D9 ON reclamation_whatsapp_session (reclamation_id)');
        $this->addSql('DROP INDEX fk_res_excursion ON reservation');
        $this->addSql('DROP INDEX fk_res_user ON reservation');
        $this->addSql('ALTER TABLE reservation CHANGE typeReservation typeReservation VARCHAR(50) NOT NULL, CHANGE statut statut VARCHAR(50) NOT NULL, CHANGE reductionPromo reductionPromo INT DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495580F22E4 FOREIGN KEY (idHebergement) REFERENCES hebergement (idHebergement) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955E69E9D09 FOREIGN KEY (id_transport) REFERENCES transport (id_transport) ON DELETE SET NULL');
        $this->addSql('DROP INDEX fk_res_hebergement ON reservation');
        $this->addSql('CREATE INDEX IDX_42C8495580F22E4 ON reservation (idHebergement)');
        $this->addSql('DROP INDEX fk_reservation_transport ON reservation');
        $this->addSql('CREATE INDEX IDX_42C84955E69E9D09 ON reservation (id_transport)');
        $this->addSql('ALTER TABLE transport CHANGE description description LONGTEXT DEFAULT NULL, CHANGE date_creation date_creation DATETIME NOT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT 0 NOT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212EE69E9D09 FOREIGN KEY (id_transport) REFERENCES transport (id_transport) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212EE3CBAF6E FOREIGN KEY (aeroport_depart_id) REFERENCES aeroport (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212E20553574 FOREIGN KEY (aeroport_destination_id) REFERENCES aeroport (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212E39A0E43A FOREIGN KEY (aeroport_prise_en_charge_id) REFERENCES aeroport (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX transport_ibfk_1 ON transport');
        $this->addSql('CREATE INDEX IDX_66AB212EE3CBAF6E ON transport (aeroport_depart_id)');
        $this->addSql('DROP INDEX transport_ibfk_2 ON transport');
        $this->addSql('CREATE INDEX IDX_66AB212E20553574 ON transport (aeroport_destination_id)');
        $this->addSql('DROP INDEX transport_ibfk_3 ON transport');
        $this->addSql('CREATE INDEX IDX_66AB212E39A0E43A ON transport (aeroport_prise_en_charge_id)');
        $this->addSql('DROP INDEX email ON utilisateur');
        $this->addSql('ALTER TABLE utilisateur DROP email_auth_code, DROP email_auth_enabled, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE prenom prenom VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(180) NOT NULL, CHANGE role role VARCHAR(50) NOT NULL, CHANGE dateInscription dateInscription DATE DEFAULT NULL, CHANGE statut statut VARCHAR(20) DEFAULT NULL, CHANGE dateCreation dateCreation DATE DEFAULT NULL, CHANGE trustScore trustScore INT DEFAULT NULL, CHANGE fidelity_points fidelity_points INT NOT NULL, CHANGE has_played_wheel has_played_wheel TINYINT NOT NULL');
        $this->addSql('ALTER TABLE wheel_spin ADD CONSTRAINT FK_A71A741EA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_A71A741EA76ED395 ON wheel_spin (user_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE login_history (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, login_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, success TINYINT NOT NULL, trust_score DOUBLE PRECISION DEFAULT NULL, face_confidence DOUBLE PRECISION DEFAULT \'0\', auth_method ENUM(\'PASSWORD\', \'FACE\') CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, fail_reason VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, device_fingerprint VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, ip_address VARCHAR(45) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, country VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, city VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, INDEX idx_user_success (user_id, success), INDEX idx_user_time (user_id, login_time), INDEX idx_user_method (user_id, auth_method), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE signalement (id INT AUTO_INCREMENT NOT NULL, post_id INT UNSIGNED NOT NULL, raison VARCHAR(60) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, details VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, statut VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT \'NOUVEAU\' COLLATE `utf8mb4_general_ci`, INDEX fk_signalement_post (post_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE reponse_reclamation DROP FOREIGN KEY FK_C7CB51012D6BA2D9');
        $this->addSql('ALTER TABLE user_favorite_excursions DROP FOREIGN KEY FK_844C773AA76ED395');
        $this->addSql('ALTER TABLE user_favorite_excursions DROP FOREIGN KEY FK_844C773A4AB4296F');
        $this->addSql('DROP TABLE reponse_reclamation');
        $this->addSql('DROP TABLE user_favorite_excursions');
        $this->addSql('ALTER TABLE aeroport CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('ALTER TABLE categorie CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE categorie_hebergement ADD image VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_nom ON categorie_hebergement (nom)');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BC4B89032C');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BCFE6E88D7');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BC4B89032C');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BCFE6E88D7');
        $this->addSql('ALTER TABLE commentaire CHANGE contenu contenu TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_67f068bc4b89032c ON commentaire');
        $this->addSql('CREATE INDEX idx_comment_post ON commentaire (post_id)');
        $this->addSql('DROP INDEX idx_67f068bcfe6e88d7 ON commentaire');
        $this->addSql('CREATE INDEX fk_commentaire_utilisateur ON commentaire (idUser)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC4B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCFE6E88D7 FOREIGN KEY (idUser) REFERENCES utilisateur (idUser) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE email_verification DROP verified, CHANGE code code VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE excursion DROP FOREIGN KEY FK_9B08E72FBCF5E72D');
        $this->addSql('ALTER TABLE excursion DROP FOREIGN KEY FK_9B08E72FBCF5E72D');
        $this->addSql('ALTER TABLE excursion CHANGE description description TEXT DEFAULT NULL, CHANGE categorie_id categorie_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX idx_9b08e72fbcf5e72d ON excursion');
        $this->addSql('CREATE INDEX fk_excursion_categorie ON excursion (categorie_id)');
        $this->addSql('ALTER TABLE excursion ADD CONSTRAINT FK_9B08E72FBCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED94AB4296F');
        $this->addSql('DROP INDEX IDX_68C58ED9A76ED395 ON favorite');
        $this->addSql('ALTER TABLE favorite DROP FOREIGN KEY FK_68C58ED94AB4296F');
        $this->addSql('ALTER TABLE favorite CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_68c58ed94ab4296f ON favorite');
        $this->addSql('CREATE INDEX fk_favorite_excursion ON favorite (excursion_id)');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED94AB4296F FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE hebergement DROP FOREIGN KEY FK_4852DD9CB597FD62');
        $this->addSql('ALTER TABLE hebergement DROP FOREIGN KEY FK_4852DD9CB597FD62');
        $this->addSql('ALTER TABLE hebergement CHANGE type type ENUM(\'HOTEL\', \'MAISON\', \'APPARTEMENT\') DEFAULT NULL, CHANGE description description TEXT NOT NULL, CHANGE disponibilite disponibilite ENUM(\'DISPONIBLE\', \'INDISPONIBLE\') DEFAULT NULL, CHANGE galleryImages galleryImages LONGTEXT DEFAULT NULL, CHANGE nb_notes nb_notes INT DEFAULT 0');
        $this->addSql('CREATE INDEX fk_hebergement_user ON hebergement (idUser)');
        $this->addSql('DROP INDEX idx_4852dd9cb597fd62 ON hebergement');
        $this->addSql('CREATE INDEX idx_hebergement_categorie ON hebergement (idCategorie)');
        $this->addSql('ALTER TABLE hebergement ADD CONSTRAINT FK_4852DD9CB597FD62 FOREIGN KEY (idCategorie) REFERENCES categorie_hebergement (idCategorie) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA2D6BA2D9');
        $this->addSql('DROP INDEX IDX_BF5476CAA76ED395 ON notification');
        $this->addSql('DROP INDEX IDX_BF5476CA2D6BA2D9 ON notification');
        $this->addSql('ALTER TABLE notification CHANGE message message VARCHAR(255) DEFAULT NULL, CHANGE is_read is_read TINYINT DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E5ADA84A2');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E5ADA84A2');
        $this->addSql('ALTER TABLE paiement CHANGE reduction reduction DOUBLE PRECISION DEFAULT \'0\'');
        $this->addSql('DROP INDEX idx_b1dc7a1e5ada84a2 ON paiement');
        $this->addSql('CREATE INDEX fk_paiement_reservation ON paiement (id_reservation)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E5ADA84A2 FOREIGN KEY (id_reservation) REFERENCES reservation (idReservation)');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DF9C28DE1');
        $this->addSql('ALTER TABLE post DROP FOREIGN KEY FK_5A8A6C8DF9C28DE1');
        $this->addSql('ALTER TABLE post CHANGE contenu contenu TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'PUBLISHED\' NOT NULL');
        $this->addSql('DROP INDEX idx_5a8a6c8df9c28de1 ON post');
        $this->addSql('CREATE INDEX fk_post_user ON post (IdUser)');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8DF9C28DE1 FOREIGN KEY (IdUser) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_like DROP FOREIGN KEY FK_653627B84B89032C');
        $this->addSql('ALTER TABLE post_like DROP FOREIGN KEY FK_653627B84B89032C');
        $this->addSql('ALTER TABLE post_like CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_653627b84b89032c ON post_like');
        $this->addSql('CREATE INDEX idx_like_post ON post_like (post_id)');
        $this->addSql('ALTER TABLE post_like ADD CONSTRAINT FK_653627B84B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promo_code DROP FOREIGN KEY FK_3D8C939EA76ED395');
        $this->addSql('ALTER TABLE promo_code ADD used TINYINT DEFAULT 0, CHANGE actif actif TINYINT DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE user_id user_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX uniq_3d8c939e77153098 ON promo_code');
        $this->addSql('CREATE UNIQUE INDEX code ON promo_code (code)');
        $this->addSql('DROP INDEX idx_3d8c939ea76ed395 ON promo_code');
        $this->addSql('CREATE INDEX idx_promo_user ON promo_code (user_id)');
        $this->addSql('ALTER TABLE promo_code ADD CONSTRAINT FK_3D8C939EA76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_question DROP FOREIGN KEY FK_6033B00B613FECDF');
        $this->addSql('ALTER TABLE quiz_question CHANGE question question TEXT NOT NULL');
        $this->addSql('DROP INDEX idx_6033b00b613fecdf ON quiz_question');
        $this->addSql('CREATE INDEX fk_question_session ON quiz_question (session_id)');
        $this->addSql('ALTER TABLE quiz_question ADD CONSTRAINT FK_6033B00B613FECDF FOREIGN KEY (session_id) REFERENCES quiz_session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE quiz_session DROP FOREIGN KEY FK_C21E7874A76ED395');
        $this->addSql('ALTER TABLE quiz_session CHANGE score score INT DEFAULT 0, CHANGE played played TINYINT DEFAULT 0');
        $this->addSql('DROP INDEX idx_c21e7874a76ed395 ON quiz_session');
        $this->addSql('CREATE INDEX fk_quiz_user ON quiz_session (user_id)');
        $this->addSql('ALTER TABLE quiz_session ADD CONSTRAINT FK_C21E7874A76ED395 FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D8892622A76ED395');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D88926224AB4296F');
        $this->addSql('ALTER TABLE rating DROP FOREIGN KEY FK_D88926224AB4296F');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT `fk_rating_excursion` FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT `fk_rating_user` FOREIGN KEY (user_id) REFERENCES utilisateur (idUser) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX unique_user_excursion ON rating (user_id, excursion_id)');
        $this->addSql('DROP INDEX idx_d88926224ab4296f ON rating');
        $this->addSql('CREATE INDEX fk_rating_excursion ON rating (excursion_id)');
        $this->addSql('ALTER TABLE rating ADD CONSTRAINT FK_D88926224AB4296F FOREIGN KEY (excursion_id) REFERENCES excursion (idExcursion)');
        $this->addSql('ALTER TABLE reclamation CHANGE description description TEXT NOT NULL, CHANGE typeReclamation typeReclamation ENUM(\'TRANSPORT\', \'LOISIR\', \'HEBERGEMENT\') NOT NULL, CHANGE dateReclamation dateReclamation DATE DEFAULT CURRENT_DATE NOT NULL, CHANGE statut statut ENUM(\'EN_ATTENTE\', \'TRAITEE\', \'REFUSEE\') DEFAULT \'EN_ATTENTE\' NOT NULL, CHANGE reponseAdmin reponseAdmin TEXT DEFAULT NULL, CHANGE priorite priorite ENUM(\'FAIBLE\', \'NORMAL\', \'URGENT\') DEFAULT \'NORMAL\'');
        $this->addSql('CREATE INDEX idx_reclamation_user ON reclamation (idUser)');
        $this->addSql('CREATE INDEX idx_reclamation_reservation ON reclamation (idReservation)');
        $this->addSql('ALTER TABLE reclamation_whatsapp_session DROP FOREIGN KEY FK_5190DD6A2D6BA2D9');
        $this->addSql('ALTER TABLE reclamation_whatsapp_session DROP FOREIGN KEY FK_5190DD6A2D6BA2D9');
        $this->addSql('ALTER TABLE reclamation_whatsapp_session CHANGE step step VARCHAR(50) DEFAULT \'awaiting_problem\', CHANGE reason reason TEXT DEFAULT NULL, CHANGE analysis_summary analysis_summary TEXT DEFAULT NULL, CHANGE turn turn INT DEFAULT 0, CHANGE is_active is_active TINYINT DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE INDEX idx_active ON reclamation_whatsapp_session (is_active)');
        $this->addSql('CREATE INDEX idx_phone ON reclamation_whatsapp_session (phone)');
        $this->addSql('DROP INDEX idx_5190dd6a2d6ba2d9 ON reclamation_whatsapp_session');
        $this->addSql('CREATE INDEX idx_reclamation ON reclamation_whatsapp_session (reclamation_id)');
        $this->addSql('ALTER TABLE reclamation_whatsapp_session ADD CONSTRAINT FK_5190DD6A2D6BA2D9 FOREIGN KEY (reclamation_id) REFERENCES reclamation (idReclamation) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C8495580F22E4');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955E69E9D09');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C8495580F22E4');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955E69E9D09');
        $this->addSql('ALTER TABLE reservation CHANGE typeReservation typeReservation ENUM(\'HEBERGEMENT\', \'EXCURSION\', \'TRANSPORT\') NOT NULL, CHANGE statut statut ENUM(\'CONFIRMEE\', \'ANNULEE\', \'EN_ATTENTE\') NOT NULL, CHANGE reductionPromo reductionPromo INT DEFAULT 0');
        $this->addSql('CREATE INDEX fk_res_excursion ON reservation (idExcursion)');
        $this->addSql('CREATE INDEX fk_res_user ON reservation (idUser)');
        $this->addSql('DROP INDEX idx_42c8495580f22e4 ON reservation');
        $this->addSql('CREATE INDEX fk_res_hebergement ON reservation (idHebergement)');
        $this->addSql('DROP INDEX idx_42c84955e69e9d09 ON reservation');
        $this->addSql('CREATE INDEX fk_reservation_transport ON reservation (id_transport)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495580F22E4 FOREIGN KEY (idHebergement) REFERENCES hebergement (idHebergement) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955E69E9D09 FOREIGN KEY (id_transport) REFERENCES transport (id_transport) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212EE69E9D09');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212EE3CBAF6E');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212E20553574');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212E39A0E43A');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212EE3CBAF6E');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212E20553574');
        $this->addSql('ALTER TABLE transport DROP FOREIGN KEY FK_66AB212E39A0E43A');
        $this->addSql('ALTER TABLE transport CHANGE description description TEXT DEFAULT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'0\' NOT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'0\' NOT NULL');
        $this->addSql('DROP INDEX idx_66ab212e20553574 ON transport');
        $this->addSql('CREATE INDEX transport_ibfk_2 ON transport (aeroport_destination_id)');
        $this->addSql('DROP INDEX idx_66ab212e39a0e43a ON transport');
        $this->addSql('CREATE INDEX transport_ibfk_3 ON transport (aeroport_prise_en_charge_id)');
        $this->addSql('DROP INDEX idx_66ab212ee3cbaf6e ON transport');
        $this->addSql('CREATE INDEX transport_ibfk_1 ON transport (aeroport_depart_id)');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212EE3CBAF6E FOREIGN KEY (aeroport_depart_id) REFERENCES aeroport (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212E20553574 FOREIGN KEY (aeroport_destination_id) REFERENCES aeroport (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transport ADD CONSTRAINT FK_66AB212E39A0E43A FOREIGN KEY (aeroport_prise_en_charge_id) REFERENCES aeroport (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE utilisateur ADD email_auth_code VARCHAR(6) DEFAULT NULL, ADD email_auth_enabled TINYINT DEFAULT 1 NOT NULL, CHANGE nom nom VARCHAR(50) NOT NULL, CHANGE prenom prenom VARCHAR(50) NOT NULL, CHANGE email email VARCHAR(100) NOT NULL, CHANGE role role ENUM(\'client\', \'admin\', \'prestataire\') NOT NULL, CHANGE dateInscription dateInscription DATE DEFAULT CURRENT_DATE NOT NULL, CHANGE statut statut ENUM(\'actif\', \'bloqué\') DEFAULT \'actif\', CHANGE dateCreation dateCreation DATE DEFAULT CURRENT_DATE, CHANGE trustScore trustScore INT DEFAULT 50, CHANGE fidelity_points fidelity_points INT DEFAULT 0 NOT NULL, CHANGE has_played_wheel has_played_wheel TINYINT DEFAULT 0');
        $this->addSql('CREATE UNIQUE INDEX email ON utilisateur (email)');
        $this->addSql('ALTER TABLE wheel_spin DROP FOREIGN KEY FK_A71A741EA76ED395');
        $this->addSql('DROP INDEX IDX_A71A741EA76ED395 ON wheel_spin');
    }
}
