<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E9xuuRPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E9xuuRP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.E9xuuRP.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.E9xuuRP": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'entityManager' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.E9xuuRP'])) {
            return $container->privates['.service_locator.E9xuuRP'];
        }

        return $container->privates['.service_locator.E9xuuRP'] = $instance;
    }
}
