<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPublicationControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.24Qf0r0.App\Controller\AdminPublicationController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'entityManager' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\AdminPublicationController::create()', $container);

        if (isset($container->privates['.service_locator.24Qf0r0.App\\Controller\\AdminPublicationController::create()'])) {
            return $container->privates['.service_locator.24Qf0r0.App\\Controller\\AdminPublicationController::create()'];
        }

        return $container->privates['.service_locator.24Qf0r0.App\\Controller\\AdminPublicationController::create()'] = $instance;
    }
}
