<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiTransportControllervalidateAirportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kqiVI3J.App\Controller\ApiTransportController::validateAirport()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kqiVI3J.App\\Controller\\ApiTransportController::validateAirport()'] = ($container->privates['.service_locator.kqiVI3J'] ?? $container->load('get_ServiceLocator_KqiVI3JService'))->withContext('App\\Controller\\ApiTransportController::validateAirport()', $container);
    }
}
