<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminReclamationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G6QsI_b.App\Controller\AdminReclamationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionRepo' => ['privates', 'App\\Repository\\ReclamationWhatsAppSessionRepository', 'getReclamationWhatsAppSessionRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'sessionRepo' => 'App\\Repository\\ReclamationWhatsAppSessionRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\AdminReclamationController::index()', $container);

        if (isset($container->privates['.service_locator.G6QsI_b.App\\Controller\\AdminReclamationController::index()'])) {
            return $container->privates['.service_locator.G6QsI_b.App\\Controller\\AdminReclamationController::index()'];
        }

        return $container->privates['.service_locator.G6QsI_b.App\\Controller\\AdminReclamationController::index()'] = $instance;
    }
}
