<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminReclamationControllerexportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AelR19G.App\Controller\AdminReclamationController::export()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AelR19G.App\\Controller\\AdminReclamationController::export()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excelService' => ['privates', 'App\\Service\\ExcelService', 'getExcelServiceService', true],
        ], [
            'excelService' => 'App\\Service\\ExcelService',
        ]))->withContext('App\\Controller\\AdminReclamationController::export()', $container);
    }
}
