<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPublicationControlleraddCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4lYT8b.App\Controller\AdminPublicationController::addComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.q4lYT8b'] ?? $container->load('get_ServiceLocator_Q4lYT8bService'));

        if (isset($container->privates['.service_locator.q4lYT8b.App\\Controller\\AdminPublicationController::addComment()'])) {
            return $container->privates['.service_locator.q4lYT8b.App\\Controller\\AdminPublicationController::addComment()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminPublicationController::addComment()', $container);

        if (isset($container->privates['.service_locator.q4lYT8b.App\\Controller\\AdminPublicationController::addComment()'])) {
            return $container->privates['.service_locator.q4lYT8b.App\\Controller\\AdminPublicationController::addComment()'];
        }

        return $container->privates['.service_locator.q4lYT8b.App\\Controller\\AdminPublicationController::addComment()'] = $instance;
    }
}
