<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCityExtractionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CityExtractionService' shared autowired service.
     *
     * @return \App\Service\CityExtractionService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\CityExtractionService": argument "$geminiApiKey" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
