<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieHebergementControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s2__bnc.App\Controller\CategorieHebergementController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.s2__bnc'] ?? $container->load('get_ServiceLocator_S2BncService'));

        if (isset($container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::delete()'])) {
            return $container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\CategorieHebergementController::delete()', $container);

        if (isset($container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::delete()'])) {
            return $container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::delete()'];
        }

        return $container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::delete()'] = $instance;
    }
}
