<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieHebergementRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\CategorieHebergementRepository' shared autowired service.
     *
     * @return \App\Repository\CategorieHebergementRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'CategorieHebergementRepository.php';

        return $container->privates['App\\Repository\\CategorieHebergementRepository'] = new \App\Repository\CategorieHebergementRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
