<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieHebergementControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eZjFflZ.App\Controller\CategorieHebergementController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eZjFflZ.App\\Controller\\CategorieHebergementController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieHebergementRepository', 'getCategorieHebergementRepositoryService', true],
        ], [
            'categorieRepo' => 'App\\Repository\\CategorieHebergementRepository',
        ]))->withContext('App\\Controller\\CategorieHebergementController::index()', $container);
    }
}
