<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dswaANm.App\Controller\CategorieController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.dswaANm'] ?? $container->load('get_ServiceLocator_DswaANmService'));

        if (isset($container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::index()'])) {
            return $container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\CategorieController::index()', $container);

        if (isset($container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::index()'])) {
            return $container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::index()'];
        }

        return $container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::index()'] = $instance;
    }
}
