<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcursionControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.myBe3wZ.App\Controller\ExcursionController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.myBe3wZ.App\\Controller\\ExcursionController::search()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ExcursionRepository',
        ]))->withContext('App\\Controller\\ExcursionController::search()', $container);
    }
}
