<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailVerificationControllersendCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KsglSSN.App\Controller\EmailVerificationController::sendCode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'mailer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\EmailVerificationController::sendCode()', $container);

        if (isset($container->privates['.service_locator.KsglSSN.App\\Controller\\EmailVerificationController::sendCode()'])) {
            return $container->privates['.service_locator.KsglSSN.App\\Controller\\EmailVerificationController::sendCode()'];
        }

        return $container->privates['.service_locator.KsglSSN.App\\Controller\\EmailVerificationController::sendCode()'] = $instance;
    }
}
