<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllerhebergementDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9xFN6.r.App\Controller\FrontOfficeController::hebergementDetail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9xFN6.r.App\\Controller\\FrontOfficeController::hebergementDetail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', false],
        ], [
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
        ]))->withContext('App\\Controller\\FrontOfficeController::hebergementDetail()', $container);
    }
}
