<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllerhebergementsByCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PmR.YNZ.App\Controller\FrontOfficeController::hebergementsByCategorie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PmR.YNZ.App\\Controller\\FrontOfficeController::hebergementsByCategorie()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieHebergementRepository', 'getCategorieHebergementRepositoryService', true],
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', false],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieHebergementRepository',
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
        ]))->withContext('App\\Controller\\FrontOfficeController::hebergementsByCategorie()', $container);
    }
}
