<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllertransportsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pzn5Gyr.App\Controller\FrontOfficeController::transports()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pzn5Gyr.App\\Controller\\FrontOfficeController::transports()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transportRepository' => ['privates', 'App\\Repository\\TransportRepository', 'getTransportRepositoryService', true],
            'aeroportRepository' => ['privates', 'App\\Repository\\AeroportRepository', 'getAeroportRepositoryService', true],
        ], [
            'transportRepository' => 'App\\Repository\\TransportRepository',
            'aeroportRepository' => 'App\\Repository\\AeroportRepository',
        ]))->withContext('App\\Controller\\FrontOfficeController::transports()', $container);
    }
}
