<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllergeneratePassImageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oY2kxn..App\Controller\FrontOfficeController::generatePassImage()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oY2kxn..App\\Controller\\FrontOfficeController::generatePassImage()'] = ($container->privates['.service_locator.oY2kxn.'] ?? $container->load('get_ServiceLocator_OY2kxn_Service'))->withContext('App\\Controller\\FrontOfficeController::generatePassImage()', $container);
    }
}
