<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllertransportDetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HrVSWCd.App\Controller\FrontOfficeController::transportDetail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transportRepository' => ['privates', 'App\\Repository\\TransportRepository', 'getTransportRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'pricingService' => ['privates', 'App\\Service\\PredictiveFareService', 'getPredictiveFareServiceService', true],
            'sjs' => ['privates', 'App\\Service\\SmartJourneySynchronizer', 'getSmartJourneySynchronizerService', true],
        ], [
            'transportRepository' => 'App\\Repository\\TransportRepository',
            'em' => '?',
            'pricingService' => 'App\\Service\\PredictiveFareService',
            'sjs' => 'App\\Service\\SmartJourneySynchronizer',
        ]))->withContext('App\\Controller\\FrontOfficeController::transportDetail()', $container);

        if (isset($container->privates['.service_locator.HrVSWCd.App\\Controller\\FrontOfficeController::transportDetail()'])) {
            return $container->privates['.service_locator.HrVSWCd.App\\Controller\\FrontOfficeController::transportDetail()'];
        }

        return $container->privates['.service_locator.HrVSWCd.App\\Controller\\FrontOfficeController::transportDetail()'] = $instance;
    }
}
