<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControlleroptimizeRouteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7Y4vLYv.App\Controller\FrontOfficeController::optimizeRoute()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Y4vLYv.App\\Controller\\FrontOfficeController::optimizeRoute()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', 'http_client.uri_template', 'getHttpClient_UriTemplateService', true],
        ], [
            'client' => '?',
        ]))->withContext('App\\Controller\\FrontOfficeController::optimizeRoute()', $container);
    }
}
