<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllerhebergementsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Iq8th1T.App\Controller\FrontOfficeController::hebergements()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Iq8th1T.App\\Controller\\FrontOfficeController::hebergements()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', false],
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieHebergementRepository', 'getCategorieHebergementRepositoryService', true],
        ], [
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
            'categorieRepository' => 'App\\Repository\\CategorieHebergementRepository',
        ]))->withContext('App\\Controller\\FrontOfficeController::hebergements()', $container);
    }
}
