<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s54Om0q.App\Controller\HebergementController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergement' => ['privates', '.errored..service_locator.s54Om0q.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.s54Om0q": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
            'em' => '?',
        ]))->withContext('App\\Controller\\HebergementController::delete()', $container);

        if (isset($container->privates['.service_locator.s54Om0q.App\\Controller\\HebergementController::delete()'])) {
            return $container->privates['.service_locator.s54Om0q.App\\Controller\\HebergementController::delete()'];
        }

        return $container->privates['.service_locator.s54Om0q.App\\Controller\\HebergementController::delete()'] = $instance;
    }
}
