<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementQpAiControlleranalyzeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.43tyyd9.App\Controller\HebergementQpAiController::analyze()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.43tyyd9.App\\Controller\\HebergementQpAiController::analyze()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiService' => ['privates', 'App\\Service\\HebergementAiService', 'getHebergementAiServiceService', true],
        ], [
            'aiService' => 'App\\Service\\HebergementAiService',
        ]))->withContext('App\\Controller\\HebergementQpAiController::analyze()', $container);
    }
}
