<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementAiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HebergementAiService' shared autowired service.
     *
     * @return \App\Service\HebergementAiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HebergementAiService.php';

        return $container->privates['App\\Service\\HebergementAiService'] = new \App\Service\HebergementAiService(($container->privates['App\\Repository\\HebergementRepository'] ?? self::getHebergementRepositoryService($container)));
    }
}
