<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementDetailControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1AnLrKS.App\Controller\HebergementDetailController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1AnLrKS.App\\Controller\\HebergementDetailController::detail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergement' => ['privates', '.errored..service_locator.1AnLrKS.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.1AnLrKS": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
        ]))->withContext('App\\Controller\\HebergementDetailController::detail()', $container);
    }
}
