<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementAiControllerrecommendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H7vCzkY.App\Controller\HebergementAiController::recommend()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H7vCzkY.App\\Controller\\HebergementAiController::recommend()'] = ($container->privates['.service_locator.H7vCzkY'] ?? $container->load('get_ServiceLocator_H7vCzkYService'))->withContext('App\\Controller\\HebergementAiController::recommend()', $container);
    }
}
