<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllerrateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kPu6JVj.App\Controller\LoisirController::rate()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\LoisirController::rate()', $container);

        if (isset($container->privates['.service_locator.kPu6JVj.App\\Controller\\LoisirController::rate()'])) {
            return $container->privates['.service_locator.kPu6JVj.App\\Controller\\LoisirController::rate()'];
        }

        return $container->privates['.service_locator.kPu6JVj.App\\Controller\\LoisirController::rate()'] = $instance;
    }
}
