<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllerexcursionsByCategorieService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z5N1T7D.App\Controller\LoisirController::excursionsByCategorie()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z5N1T7D.App\\Controller\\LoisirController::excursionsByCategorie()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]))->withContext('App\\Controller\\LoisirController::excursionsByCategorie()', $container);
    }
}
