<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllerreserverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rk9_dUq.App\Controller\LoisirController::reserver()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rk9_dUq.App\\Controller\\LoisirController::reserver()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
        ], [
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
        ]))->withContext('App\\Controller\\LoisirController::reserver()', $container);
    }
}
