<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllermeteoByExcursionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5FJ777H.App\Controller\LoisirController::meteoByExcursion()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5FJ777H.App\\Controller\\LoisirController::meteoByExcursion()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'weatherService' => ['privates', 'App\\Service\\WeatherService', 'getWeatherServiceService', true],
        ], [
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'weatherService' => 'App\\Service\\WeatherService',
        ]))->withContext('App\\Controller\\LoisirController::meteoByExcursion()', $container);
    }
}
