<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllermesFavorisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wBXET56.App\Controller\LoisirController::mesFavoris()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wBXET56.App\\Controller\\LoisirController::mesFavoris()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\FavoriteRepository',
        ]))->withContext('App\\Controller\\LoisirController::mesFavoris()', $container);
    }
}
