<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllerdetailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bCusjL5.App\Controller\LoisirController::detail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bCusjL5.App\\Controller\\LoisirController::detail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'prixService' => ['privates', 'App\\Service\\PrixIntelligentService', 'getPrixIntelligentServiceService', true],
            'promoRepo' => ['privates', 'App\\Repository\\PromoCodeRepository', 'getPromoCodeRepositoryService', true],
        ], [
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'prixService' => 'App\\Service\\PrixIntelligentService',
            'promoRepo' => 'App\\Repository\\PromoCodeRepository',
        ]))->withContext('App\\Controller\\LoisirController::detail()', $container);
    }
}
