<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMesReservationsControllertransportsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6vVaFyG.App\Controller\MesReservationsController::transports()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6vVaFyG.App\\Controller\\MesReservationsController::transports()'] = ($container->privates['.service_locator.6vVaFyG'] ?? $container->load('get_ServiceLocator_6vVaFyGService'))->withContext('App\\Controller\\MesReservationsController::transports()', $container);
    }
}
