<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoCodeControllerapplyPromoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N7_.MZ4.App\Controller\PromoCodeController::applyPromo()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N7_.MZ4.App\\Controller\\PromoCodeController::applyPromo()'] = ($container->privates['.service_locator.N7_.MZ4'] ?? $container->load('get_ServiceLocator_N7_MZ4Service'))->withContext('App\\Controller\\PromoCodeController::applyPromo()', $container);
    }
}
