<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControlleraddCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tjOlJ2D.App\Controller\PostController::addComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'badWordsFilterService' => ['privates', 'App\\Service\\BadWordsFilterService', 'getBadWordsFilterServiceService', true],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'entityManager' => '?',
            'badWordsFilterService' => 'App\\Service\\BadWordsFilterService',
        ]))->withContext('App\\Controller\\PostController::addComment()', $container);

        if (isset($container->privates['.service_locator.tjOlJ2D.App\\Controller\\PostController::addComment()'])) {
            return $container->privates['.service_locator.tjOlJ2D.App\\Controller\\PostController::addComment()'];
        }

        return $container->privates['.service_locator.tjOlJ2D.App\\Controller\\PostController::addComment()'] = $instance;
    }
}
