<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaiementControllersuccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c4j7NHV.App\Controller\PaiementController::success()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'emailService' => ['privates', 'App\\Service\\EmailService', 'getEmailServiceService', true],
        ], [
            'em' => '?',
            'emailService' => 'App\\Service\\EmailService',
        ]))->withContext('App\\Controller\\PaiementController::success()', $container);

        if (isset($container->privates['.service_locator.c4j7NHV.App\\Controller\\PaiementController::success()'])) {
            return $container->privates['.service_locator.c4j7NHV.App\\Controller\\PaiementController::success()'];
        }

        return $container->privates['.service_locator.c4j7NHV.App\\Controller\\PaiementController::success()'] = $instance;
    }
}
