<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrixIntelligentServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PrixIntelligentService' shared autowired service.
     *
     * @return \App\Service\PrixIntelligentService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PrixIntelligentService.php';

        return $container->privates['App\\Service\\PrixIntelligentService'] = new \App\Service\PrixIntelligentService(($container->privates['App\\Service\\WeatherService'] ?? $container->load('getWeatherServiceService')));
    }
}
