<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZyTlAJo.App\Controller\ProfileController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fidelityService' => ['privates', 'App\\Service\\FidelityService', 'getFidelityServiceService', true],
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'quizRepo' => ['privates', 'App\\Repository\\QuizSessionRepository', 'getQuizSessionRepositoryService', true],
            'fraud' => ['privates', 'App\\Service\\FraudDetectionService', 'getFraudDetectionServiceService', true],
            'wheelRepo' => ['privates', 'App\\Repository\\WheelSpinRepository', 'getWheelSpinRepositoryService', true],
        ], [
            'fidelityService' => 'App\\Service\\FidelityService',
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'quizRepo' => 'App\\Repository\\QuizSessionRepository',
            'fraud' => 'App\\Service\\FraudDetectionService',
            'wheelRepo' => 'App\\Repository\\WheelSpinRepository',
        ]))->withContext('App\\Controller\\ProfileController::index()', $container);

        if (isset($container->privates['.service_locator.ZyTlAJo.App\\Controller\\ProfileController::index()'])) {
            return $container->privates['.service_locator.ZyTlAJo.App\\Controller\\ProfileController::index()'];
        }

        return $container->privates['.service_locator.ZyTlAJo.App\\Controller\\ProfileController::index()'] = $instance;
    }
}
