<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QuizService' shared autowired service.
     *
     * @return \App\Service\QuizService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QuizService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GeminiService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\QuizService'])) {
            return $container->privates['App\\Service\\QuizService'];
        }

        $instance = new \App\Service\QuizService(($container->privates['App\\Repository\\QuizSessionRepository'] ?? $container->load('getQuizSessionRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')), new \App\Service\GeminiService(), $a);

        if (isset($container->privates['App\\Service\\QuizService'])) {
            return $container->privates['App\\Service\\QuizService'];
        }

        return $container->privates['App\\Service\\QuizService'] = $instance;
    }
}
