<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizControllersubmitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0ISeYE4.App\Controller\QuizController::submit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quizService' => ['privates', 'App\\Service\\QuizService', 'getQuizServiceService', true],
            'questionRepo' => ['privates', 'App\\Repository\\QuizQuestionRepository', 'getQuizQuestionRepositoryService', true],
            'sessionRepo' => ['privates', 'App\\Repository\\QuizSessionRepository', 'getQuizSessionRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'quizService' => 'App\\Service\\QuizService',
            'questionRepo' => 'App\\Repository\\QuizQuestionRepository',
            'sessionRepo' => 'App\\Repository\\QuizSessionRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\QuizController::submit()', $container);

        if (isset($container->privates['.service_locator.0ISeYE4.App\\Controller\\QuizController::submit()'])) {
            return $container->privates['.service_locator.0ISeYE4.App\\Controller\\QuizController::submit()'];
        }

        return $container->privates['.service_locator.0ISeYE4.App\\Controller\\QuizController::submit()'] = $instance;
    }
}
