<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllerreserverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LR.s9G3.App\Controller\ReservationController::reserver()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'prixService' => ['privates', 'App\\Service\\PrixIntelligentService', 'getPrixIntelligentServiceService', true],
        ], [
            'em' => '?',
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'prixService' => 'App\\Service\\PrixIntelligentService',
        ]))->withContext('App\\Controller\\ReservationController::reserver()', $container);

        if (isset($container->privates['.service_locator.LR.s9G3.App\\Controller\\ReservationController::reserver()'])) {
            return $container->privates['.service_locator.LR.s9G3.App\\Controller\\ReservationController::reserver()'];
        }

        return $container->privates['.service_locator.LR.s9G3.App\\Controller\\ReservationController::reserver()'] = $instance;
    }
}
