<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R5xY4Z_.App\Controller\ReservationController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergement' => ['privates', '.errored..service_locator.R5xY4Z_.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.R5xY4Z_": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded because it\'s a Doctrine entity.'],
            'hebergementRepository' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
            'hebergementRepository' => 'App\\Repository\\HebergementRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\ReservationController::create()', $container);

        if (isset($container->privates['.service_locator.R5xY4Z_.App\\Controller\\ReservationController::create()'])) {
            return $container->privates['.service_locator.R5xY4Z_.App\\Controller\\ReservationController::create()'];
        }

        return $container->privates['.service_locator.R5xY4Z_.App\\Controller\\ReservationController::create()'] = $instance;
    }
}
