<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmartJourneySynchronizerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SmartJourneySynchronizer' shared autowired service.
     *
     * @return \App\Service\SmartJourneySynchronizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SmartJourneySynchronizer.php';

        return $container->privates['App\\Service\\SmartJourneySynchronizer'] = new \App\Service\SmartJourneySynchronizer(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
