<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllerextractAirportsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a2oxt.B.App\Controller\TransportController::extractAirports()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a2oxt.B.App\\Controller\\TransportController::extractAirports()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cityExtractor' => ['privates', 'App\\Service\\CityExtractionService', NULL, 'Cannot autowire service "App\\Service\\CityExtractionService": argument "$geminiApiKey" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
            'aeroportRepo' => ['privates', 'App\\Repository\\AeroportRepository', 'getAeroportRepositoryService', true],
        ], [
            'cityExtractor' => 'App\\Service\\CityExtractionService',
            'aeroportRepo' => 'App\\Repository\\AeroportRepository',
        ]))->withContext('App\\Controller\\TransportController::extractAirports()', $container);
    }
}
