<?php

namespace ContainerOkCg2TL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhatsAppControllerreceiveService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7Uce31j.App\Controller\WhatsAppController::receive()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionRepository' => ['privates', 'App\\Repository\\ReclamationWhatsAppSessionRepository', 'getReclamationWhatsAppSessionRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'sessionRepository' => 'App\\Repository\\ReclamationWhatsAppSessionRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\WhatsAppController::receive()', $container);

        if (isset($container->privates['.service_locator.7Uce31j.App\\Controller\\WhatsAppController::receive()'])) {
            return $container->privates['.service_locator.7Uce31j.App\\Controller\\WhatsAppController::receive()'];
        }

        return $container->privates['.service_locator.7Uce31j.App\\Controller\\WhatsAppController::receive()'] = $instance;
    }
}
