<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S2BncService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s2__bnc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorie' => ['privates', '.errored..service_locator.s2__bnc.App\\Entity\\CategorieHebergement', NULL, 'Cannot autowire service ".service_locator.s2__bnc": it needs an instance of "App\\Entity\\CategorieHebergement" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorie' => 'App\\Entity\\CategorieHebergement',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.s2__bnc'])) {
            return $container->privates['.service_locator.s2__bnc'];
        }

        return $container->privates['.service_locator.s2__bnc'] = $instance;
    }
}
