<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KqiVI3JService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kqiVI3J' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kqiVI3J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aeroportRepository' => ['privates', 'App\\Repository\\AeroportRepository', 'getAeroportRepositoryService', true],
        ], [
            'aeroportRepository' => 'App\\Repository\\AeroportRepository',
        ]);
    }
}
