<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OY2kxn_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oY2kxn.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oY2kxn.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transport' => ['privates', '.errored..service_locator.oY2kxn..App\\Entity\\Transport', NULL, 'Cannot autowire service ".service_locator.oY2kxn.": it needs an instance of "App\\Entity\\Transport" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'transport' => 'App\\Entity\\Transport',
        ]);
    }
}
