<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N7_MZ4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N7_.MZ4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N7_.MZ4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'promoRepo' => ['privates', 'App\\Repository\\PromoCodeRepository', 'getPromoCodeRepositoryService', true],
        ], [
            'promoRepo' => 'App\\Repository\\PromoCodeRepository',
        ]);
    }
}
