<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AHuuTtBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AHuuTtB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.AHuuTtB.App\\Entity\\Commentaire', NULL, 'Cannot autowire service ".service_locator.AHuuTtB": it needs an instance of "App\\Entity\\Commentaire" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'comment' => 'App\\Entity\\Commentaire',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.AHuuTtB'])) {
            return $container->privates['.service_locator.AHuuTtB'];
        }

        return $container->privates['.service_locator.AHuuTtB'] = $instance;
    }
}
