<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TD3xa8XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TD3xa8X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'commentaireRepository' => ['privates', 'App\\Repository\\CommentaireRepository', 'getCommentaireRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'commentaireRepository' => 'App\\Repository\\CommentaireRepository',
            'entityManager' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.TD3xa8X'])) {
            return $container->privates['.service_locator.TD3xa8X'];
        }

        return $container->privates['.service_locator.TD3xa8X'] = $instance;
    }
}
