<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0Jt9vJqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Jt9vJq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Jt9vJq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recommandationService' => ['privates', 'App\\Service\\RecommandationService', 'getRecommandationServiceService', true],
            'prixService' => ['privates', 'App\\Service\\PrixIntelligentService', 'getPrixIntelligentServiceService', true],
            'weatherService' => ['privates', 'App\\Service\\WeatherService', 'getWeatherServiceService', true],
        ], [
            'recommandationService' => 'App\\Service\\RecommandationService',
            'prixService' => 'App\\Service\\PrixIntelligentService',
            'weatherService' => 'App\\Service\\WeatherService',
        ]);
    }
}
