<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AdF5Fz2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AdF5Fz2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.AdF5Fz2.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.AdF5Fz2": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.AdF5Fz2'])) {
            return $container->privates['.service_locator.AdF5Fz2'];
        }

        return $container->privates['.service_locator.AdF5Fz2'] = $instance;
    }
}
