<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllergetNearbyAirportsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3ZhQQrD.App\Controller\ApiController::getNearbyAirports()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3ZhQQrD.App\\Controller\\ApiController::getNearbyAirports()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cityExtractor' => ['privates', 'App\\Service\\CityExtractor', 'getCityExtractorService', true],
            'aeroportRepository' => ['privates', 'App\\Repository\\AeroportRepository', 'getAeroportRepositoryService', true],
        ], [
            'cityExtractor' => 'App\\Service\\CityExtractor',
            'aeroportRepository' => 'App\\Repository\\AeroportRepository',
        ]))->withContext('App\\Controller\\ApiController::getNearbyAirports()', $container);
    }
}
