<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPublicationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TD3xa8X.App\Controller\AdminPublicationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.TD3xa8X'] ?? $container->load('get_ServiceLocator_TD3xa8XService'));

        if (isset($container->privates['.service_locator.TD3xa8X.App\\Controller\\AdminPublicationController::index()'])) {
            return $container->privates['.service_locator.TD3xa8X.App\\Controller\\AdminPublicationController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminPublicationController::index()', $container);

        if (isset($container->privates['.service_locator.TD3xa8X.App\\Controller\\AdminPublicationController::index()'])) {
            return $container->privates['.service_locator.TD3xa8X.App\\Controller\\AdminPublicationController::index()'];
        }

        return $container->privates['.service_locator.TD3xa8X.App\\Controller\\AdminPublicationController::index()'] = $instance;
    }
}
