<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminReservationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AdF5Fz2.App\Controller\Admin\AdminReservationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AdF5Fz2'] ?? $container->load('get_ServiceLocator_AdF5Fz2Service'));

        if (isset($container->privates['.service_locator.AdF5Fz2.App\\Controller\\Admin\\AdminReservationController::edit()'])) {
            return $container->privates['.service_locator.AdF5Fz2.App\\Controller\\Admin\\AdminReservationController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\AdminReservationController::edit()', $container);

        if (isset($container->privates['.service_locator.AdF5Fz2.App\\Controller\\Admin\\AdminReservationController::edit()'])) {
            return $container->privates['.service_locator.AdF5Fz2.App\\Controller\\Admin\\AdminReservationController::edit()'];
        }

        return $container->privates['.service_locator.AdF5Fz2.App\\Controller\\Admin\\AdminReservationController::edit()'] = $instance;
    }
}
