<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminPublicationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E9xuuRP.App\Controller\AdminPublicationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.E9xuuRP'] ?? $container->load('get_ServiceLocator_E9xuuRPService'));

        if (isset($container->privates['.service_locator.E9xuuRP.App\\Controller\\AdminPublicationController::edit()'])) {
            return $container->privates['.service_locator.E9xuuRP.App\\Controller\\AdminPublicationController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\AdminPublicationController::edit()', $container);

        if (isset($container->privates['.service_locator.E9xuuRP.App\\Controller\\AdminPublicationController::edit()'])) {
            return $container->privates['.service_locator.E9xuuRP.App\\Controller\\AdminPublicationController::edit()'];
        }

        return $container->privates['.service_locator.E9xuuRP.App\\Controller\\AdminPublicationController::edit()'] = $instance;
    }
}
