<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminWhatsAppSessionControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.saNMtka.App\Controller\AdminWhatsAppSessionController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.saNMtka.App\\Controller\\AdminWhatsAppSessionController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ReclamationWhatsAppSessionRepository', 'getReclamationWhatsAppSessionRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\ReclamationWhatsAppSessionRepository',
        ]))->withContext('App\\Controller\\AdminWhatsAppSessionController::index()', $container);
    }
}
