<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dswaANm.App\Controller\CategorieController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.dswaANm'] ?? $container->load('get_ServiceLocator_DswaANmService'));

        if (isset($container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::edit()'])) {
            return $container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\CategorieController::edit()', $container);

        if (isset($container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::edit()'])) {
            return $container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::edit()'];
        }

        return $container->privates['.service_locator.dswaANm.App\\Controller\\CategorieController::edit()'] = $instance;
    }
}
