<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieHebergementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.s2__bnc.App\Entity\CategorieHebergement' shared service.
     *
     * @return \App\Entity\CategorieHebergement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.s2__bnc": it needs an instance of "App\\Entity\\CategorieHebergement" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
