<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieHebergementControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s2__bnc.App\Controller\CategorieHebergementController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.s2__bnc'] ?? $container->load('get_ServiceLocator_S2BncService'));

        if (isset($container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::edit()'])) {
            return $container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::edit()'];
        }

        $instance = $a->withContext('App\\Controller\\CategorieHebergementController::edit()', $container);

        if (isset($container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::edit()'])) {
            return $container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::edit()'];
        }

        return $container->privates['.service_locator.s2__bnc.App\\Controller\\CategorieHebergementController::edit()'] = $instance;
    }
}
