<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcursionControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K68VZ6l.App\Controller\ExcursionController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.K68VZ6l'] ?? $container->load('get_ServiceLocator_K68VZ6lService'));

        if (isset($container->privates['.service_locator.K68VZ6l.App\\Controller\\ExcursionController::delete()'])) {
            return $container->privates['.service_locator.K68VZ6l.App\\Controller\\ExcursionController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\ExcursionController::delete()', $container);

        if (isset($container->privates['.service_locator.K68VZ6l.App\\Controller\\ExcursionController::delete()'])) {
            return $container->privates['.service_locator.K68VZ6l.App\\Controller\\ExcursionController::delete()'];
        }

        return $container->privates['.service_locator.K68VZ6l.App\\Controller\\ExcursionController::delete()'] = $instance;
    }
}
