<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcursionRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ExcursionRepository' shared autowired service.
     *
     * @return \App\Repository\ExcursionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'ExcursionRepository.php';

        return $container->privates['App\\Repository\\ExcursionRepository'] = new \App\Repository\ExcursionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
