<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForgotPasswordControllersendCodeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TsQRRoY.App\Controller\ForgotPasswordController::sendCode()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'em' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\ForgotPasswordController::sendCode()', $container);

        if (isset($container->privates['.service_locator.TsQRRoY.App\\Controller\\ForgotPasswordController::sendCode()'])) {
            return $container->privates['.service_locator.TsQRRoY.App\\Controller\\ForgotPasswordController::sendCode()'];
        }

        return $container->privates['.service_locator.TsQRRoY.App\\Controller\\ForgotPasswordController::sendCode()'] = $instance;
    }
}
