<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFraudDetectionControllersmartLoginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J3VOPZF.App\Controller\FraudDetectionController::smartLogin()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fraud' => ['privates', 'App\\Service\\FraudDetectionService', 'getFraudDetectionServiceService', true],
            'geo' => ['privates', 'App\\Service\\GeoLocationService', 'getGeoLocationServiceService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'em' => '?',
            'fraud' => 'App\\Service\\FraudDetectionService',
            'geo' => 'App\\Service\\GeoLocationService',
            'tokenStorage' => '?',
        ]))->withContext('App\\Controller\\FraudDetectionController::smartLogin()', $container);

        if (isset($container->privates['.service_locator.J3VOPZF.App\\Controller\\FraudDetectionController::smartLogin()'])) {
            return $container->privates['.service_locator.J3VOPZF.App\\Controller\\FraudDetectionController::smartLogin()'];
        }

        return $container->privates['.service_locator.J3VOPZF.App\\Controller\\FraudDetectionController::smartLogin()'] = $instance;
    }
}
