<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllertransportsMapDataService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UJkdg3i.App\Controller\FrontOfficeController::transportsMapData()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UJkdg3i.App\\Controller\\FrontOfficeController::transportsMapData()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transportRepository' => ['privates', 'App\\Repository\\TransportRepository', 'getTransportRepositoryService', true],
            'aeroportRepository' => ['privates', 'App\\Repository\\AeroportRepository', 'getAeroportRepositoryService', true],
            'cache' => ['services', 'cache.app', 'getCache_AppService', false],
        ], [
            'transportRepository' => 'App\\Repository\\TransportRepository',
            'aeroportRepository' => 'App\\Repository\\AeroportRepository',
            'cache' => '?',
        ]))->withContext('App\\Controller\\FrontOfficeController::transportsMapData()', $container);
    }
}
