<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriteControllertoggleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JNii6Wi.App\Controller\FavoriteController::toggle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\FavoriteController::toggle()', $container);

        if (isset($container->privates['.service_locator.JNii6Wi.App\\Controller\\FavoriteController::toggle()'])) {
            return $container->privates['.service_locator.JNii6Wi.App\\Controller\\FavoriteController::toggle()'];
        }

        return $container->privates['.service_locator.JNii6Wi.App\\Controller\\FavoriteController::toggle()'] = $instance;
    }
}
