<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontOfficeControllersmartJourneySyncService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k4v_lTl.App\Controller\FrontOfficeController::smartJourneySync()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k4v_lTl.App\\Controller\\FrontOfficeController::smartJourneySync()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sjs' => ['privates', 'App\\Service\\SmartJourneySynchronizer', 'getSmartJourneySynchronizerService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'transportRepository' => ['privates', 'App\\Repository\\TransportRepository', 'getTransportRepositoryService', true],
        ], [
            'sjs' => 'App\\Service\\SmartJourneySynchronizer',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'transportRepository' => 'App\\Repository\\TransportRepository',
        ]))->withContext('App\\Controller\\FrontOfficeController::smartJourneySync()', $container);
    }
}
