<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFidelityServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FidelityService' shared autowired service.
     *
     * @return \App\Service\FidelityService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FidelityService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\FidelityService'])) {
            return $container->privates['App\\Service\\FidelityService'];
        }

        $instance = new \App\Service\FidelityService($a, ($container->privates['App\\Repository\\PromoCodeRepository'] ?? $container->load('getPromoCodeRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')));

        if (isset($container->privates['App\\Service\\FidelityService'])) {
            return $container->privates['App\\Service\\FidelityService'];
        }

        return $container->privates['App\\Service\\FidelityService'] = $instance;
    }
}
