<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.avNj0W9.App\Controller\HebergementController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hebergement' => ['privates', '.errored..service_locator.avNj0W9.App\\Entity\\Hebergement', NULL, 'Cannot autowire service ".service_locator.avNj0W9": it needs an instance of "App\\Entity\\Hebergement" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'hebergement' => 'App\\Entity\\Hebergement',
            'em' => '?',
            'slugger' => '?',
        ]))->withContext('App\\Controller\\HebergementController::edit()', $container);

        if (isset($container->privates['.service_locator.avNj0W9.App\\Controller\\HebergementController::edit()'])) {
            return $container->privates['.service_locator.avNj0W9.App\\Controller\\HebergementController::edit()'];
        }

        return $container->privates['.service_locator.avNj0W9.App\\Controller\\HebergementController::edit()'] = $instance;
    }
}
