<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementControlleranalyzeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TaJeOgi.App\Controller\HebergementController::analyze()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TaJeOgi.App\\Controller\\HebergementController::analyze()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assistant' => ['privates', 'App\\Service\\HebergementAiAssistant', 'getHebergementAiAssistantService', true],
        ], [
            'assistant' => 'App\\Service\\HebergementAiAssistant',
        ]))->withContext('App\\Controller\\HebergementController::analyze()', $container);
    }
}
