<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHebergementAiAssistantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\HebergementAiAssistant' shared autowired service.
     *
     * @return \App\Service\HebergementAiAssistant
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'HebergementAiAssistant.php';

        return $container->privates['App\\Service\\HebergementAiAssistant'] = new \App\Service\HebergementAiAssistant(\dirname(__DIR__, 4));
    }
}
