<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9c6323i.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wheelRepo' => ['privates', 'App\\Repository\\WheelSpinRepository', 'getWheelSpinRepositoryService', true],
            'quizService' => ['privates', 'App\\Service\\QuizService', 'getQuizServiceService', true],
            'questionRepo' => ['privates', 'App\\Repository\\QuizQuestionRepository', 'getQuizQuestionRepositoryService', true],
            'sessionRepo' => ['privates', 'App\\Repository\\QuizSessionRepository', 'getQuizSessionRepositoryService', true],
        ], [
            'wheelRepo' => 'App\\Repository\\WheelSpinRepository',
            'quizService' => 'App\\Service\\QuizService',
            'questionRepo' => 'App\\Repository\\QuizQuestionRepository',
            'sessionRepo' => 'App\\Repository\\QuizSessionRepository',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);

        if (isset($container->privates['.service_locator.9c6323i.App\\Controller\\HomeController::index()'])) {
            return $container->privates['.service_locator.9c6323i.App\\Controller\\HomeController::index()'];
        }

        return $container->privates['.service_locator.9c6323i.App\\Controller\\HomeController::index()'] = $instance;
    }
}
