<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bo.QOus.App\Controller\LoisirController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bo.QOus.App\\Controller\\LoisirController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'excursionRepository' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'weatherService' => ['privates', 'App\\Service\\WeatherService', 'getWeatherServiceService', true],
            'prixService' => ['privates', 'App\\Service\\PrixIntelligentService', 'getPrixIntelligentServiceService', true],
            'recommandationService' => ['privates', 'App\\Service\\RecommandationService', 'getRecommandationServiceService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'excursionRepository' => 'App\\Repository\\ExcursionRepository',
            'weatherService' => 'App\\Service\\WeatherService',
            'prixService' => 'App\\Service\\PrixIntelligentService',
            'recommandationService' => 'App\\Service\\RecommandationService',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]))->withContext('App\\Controller\\LoisirController::index()', $container);
    }
}
