<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoisirControllersearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OBt7QZx.App\Controller\LoisirController::search()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OBt7QZx.App\\Controller\\LoisirController::search()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'weatherService' => ['privates', 'App\\Service\\WeatherService', 'getWeatherServiceService', true],
        ], [
            'repo' => 'App\\Repository\\ExcursionRepository',
            'weatherService' => 'App\\Service\\WeatherService',
        ]))->withContext('App\\Controller\\LoisirController::search()', $container);
    }
}
