<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllermarkAsReadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hvwD_jg.App\Controller\NotificationController::markAsRead()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', false],
        ], [
            'repo' => 'App\\Repository\\NotificationRepository',
            'em' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\NotificationController::markAsRead()', $container);

        if (isset($container->privates['.service_locator.hvwD_jg.App\\Controller\\NotificationController::markAsRead()'])) {
            return $container->privates['.service_locator.hvwD_jg.App\\Controller\\NotificationController::markAsRead()'];
        }

        return $container->privates['.service_locator.hvwD_jg.App\\Controller\\NotificationController::markAsRead()'] = $instance;
    }
}
