<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerdeleteCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AHuuTtB.App\Controller\PostController::deleteComment()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.AHuuTtB'] ?? $container->load('get_ServiceLocator_AHuuTtBService'));

        if (isset($container->privates['.service_locator.AHuuTtB.App\\Controller\\PostController::deleteComment()'])) {
            return $container->privates['.service_locator.AHuuTtB.App\\Controller\\PostController::deleteComment()'];
        }

        $instance = $a->withContext('App\\Controller\\PostController::deleteComment()', $container);

        if (isset($container->privates['.service_locator.AHuuTtB.App\\Controller\\PostController::deleteComment()'])) {
            return $container->privates['.service_locator.AHuuTtB.App\\Controller\\PostController::deleteComment()'];
        }

        return $container->privates['.service_locator.AHuuTtB.App\\Controller\\PostController::deleteComment()'] = $instance;
    }
}
