<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q4lYT8b.App\Controller\PostController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.q4lYT8b'] ?? $container->load('get_ServiceLocator_Q4lYT8bService'));

        if (isset($container->privates['.service_locator.q4lYT8b.App\\Controller\\PostController::delete()'])) {
            return $container->privates['.service_locator.q4lYT8b.App\\Controller\\PostController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\PostController::delete()', $container);

        if (isset($container->privates['.service_locator.q4lYT8b.App\\Controller\\PostController::delete()'])) {
            return $container->privates['.service_locator.q4lYT8b.App\\Controller\\PostController::delete()'];
        }

        return $container->privates['.service_locator.q4lYT8b.App\\Controller\\PostController::delete()'] = $instance;
    }
}
