<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllertoggleLikeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J6pr7m_.App\Controller\PostController::toggleLike()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'postLikeRepository' => ['privates', 'App\\Repository\\PostLikeRepository', 'getPostLikeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'postLikeRepository' => 'App\\Repository\\PostLikeRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\PostController::toggleLike()', $container);

        if (isset($container->privates['.service_locator.J6pr7m_.App\\Controller\\PostController::toggleLike()'])) {
            return $container->privates['.service_locator.J6pr7m_.App\\Controller\\PostController::toggleLike()'];
        }

        return $container->privates['.service_locator.J6pr7m_.App\\Controller\\PostController::toggleLike()'] = $instance;
    }
}
