<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoCodeControllergeneratePromoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zd03KzC.App\Controller\PromoCodeController::generatePromo()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'promoRepo' => ['privates', 'App\\Repository\\PromoCodeRepository', 'getPromoCodeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'promoRepo' => 'App\\Repository\\PromoCodeRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\PromoCodeController::generatePromo()', $container);

        if (isset($container->privates['.service_locator.zd03KzC.App\\Controller\\PromoCodeController::generatePromo()'])) {
            return $container->privates['.service_locator.zd03KzC.App\\Controller\\PromoCodeController::generatePromo()'];
        }

        return $container->privates['.service_locator.zd03KzC.App\\Controller\\PromoCodeController::generatePromo()'] = $instance;
    }
}
