<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllerreportPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KcLeFBe.App\Controller\PostController::reportPost()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'smsService' => ['privates', 'App\\Service\\SmsService', 'getSmsServiceService', true],
        ], [
            'em' => '?',
            'smsService' => 'App\\Service\\SmsService',
        ]))->withContext('App\\Controller\\PostController::reportPost()', $container);

        if (isset($container->privates['.service_locator.KcLeFBe.App\\Controller\\PostController::reportPost()'])) {
            return $container->privates['.service_locator.KcLeFBe.App\\Controller\\PostController::reportPost()'];
        }

        return $container->privates['.service_locator.KcLeFBe.App\\Controller\\PostController::reportPost()'] = $instance;
    }
}
