<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p2aa3y3.App\Controller\QuizController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'quizService' => ['privates', 'App\\Service\\QuizService', 'getQuizServiceService', true],
        ], [
            'quizService' => 'App\\Service\\QuizService',
        ]))->withContext('App\\Controller\\QuizController::index()', $container);

        if (isset($container->privates['.service_locator.p2aa3y3.App\\Controller\\QuizController::index()'])) {
            return $container->privates['.service_locator.p2aa3y3.App\\Controller\\QuizController::index()'];
        }

        return $container->privates['.service_locator.p2aa3y3.App\\Controller\\QuizController::index()'] = $instance;
    }
}
