<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommandationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0Jt9vJq.App\Controller\RecommandationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0Jt9vJq.App\\Controller\\RecommandationController::index()'] = ($container->privates['.service_locator.0Jt9vJq'] ?? $container->load('get_ServiceLocator_0Jt9vJqService'))->withContext('App\\Controller\\RecommandationController::index()', $container);
    }
}
