<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllerprixIntelligentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bjkUR61.App\Controller\ReservationController::prixIntelligent()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bjkUR61.App\\Controller\\ReservationController::prixIntelligent()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\ExcursionRepository', 'getExcursionRepositoryService', true],
            'service' => ['privates', 'App\\Service\\PrixIntelligentService', 'getPrixIntelligentServiceService', true],
        ], [
            'repo' => 'App\\Repository\\ExcursionRepository',
            'service' => 'App\\Service\\PrixIntelligentService',
        ]))->withContext('App\\Controller\\ReservationController::prixIntelligent()', $container);
    }
}
