<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReclamationControlleradminIndexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._6xWKRD.App\Controller\ReclamationController::adminIndex()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]))->withContext('App\\Controller\\ReclamationController::adminIndex()', $container);

        if (isset($container->privates['.service_locator._6xWKRD.App\\Controller\\ReclamationController::adminIndex()'])) {
            return $container->privates['.service_locator._6xWKRD.App\\Controller\\ReclamationController::adminIndex()'];
        }

        return $container->privates['.service_locator._6xWKRD.App\\Controller\\ReclamationController::adminIndex()'] = $instance;
    }
}
