<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommandationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RecommandationService' shared autowired service.
     *
     * @return \App\Service\RecommandationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'RecommandationService.php';

        return $container->privates['App\\Service\\RecommandationService'] = new \App\Service\RecommandationService(($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')), ($container->privates['App\\Repository\\ExcursionRepository'] ?? $container->load('getExcursionRepositoryService')), $container->getEnv('GEMINI_API_KEY'));
    }
}
