<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllerconfirmationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sqmCeW5.App\Controller\ReservationController::confirmation()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sqmCeW5.App\\Controller\\ReservationController::confirmation()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepo' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'hebergementRepo' => ['privates', 'App\\Repository\\HebergementRepository', 'getHebergementRepositoryService', false],
        ], [
            'reservationRepo' => 'App\\Repository\\ReservationRepository',
            'hebergementRepo' => 'App\\Repository\\HebergementRepository',
        ]))->withContext('App\\Controller\\ReservationController::confirmation()', $container);
    }
}
