<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmartJourneyControllersynchronizeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ulc_X0w.App\Controller\SmartJourneyController::synchronize()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ulc_X0w.App\\Controller\\SmartJourneyController::synchronize()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sjs' => ['privates', 'App\\Service\\SmartJourneySynchronizer', 'getSmartJourneySynchronizerService', true],
        ], [
            'sjs' => 'App\\Service\\SmartJourneySynchronizer',
        ]))->withContext('App\\Controller\\SmartJourneyController::synchronize()', $container);
    }
}
