<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllerhebergementsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4hfk0bD.App\Controller\TransportController::hebergements()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4hfk0bD.App\\Controller\\TransportController::hebergements()'] = ($container->privates['.service_locator.4hfk0bD'] ?? $container->load('get_ServiceLocator_4hfk0bDService'))->withContext('App\\Controller\\TransportController::hebergements()', $container);
    }
}
