<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllerdeleteTransportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wUUQci5.App\Controller\TransportController::deleteTransport()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.wUUQci5'] ?? $container->load('get_ServiceLocator_WUUQci5Service'));

        if (isset($container->privates['.service_locator.wUUQci5.App\\Controller\\TransportController::deleteTransport()'])) {
            return $container->privates['.service_locator.wUUQci5.App\\Controller\\TransportController::deleteTransport()'];
        }

        $instance = $a->withContext('App\\Controller\\TransportController::deleteTransport()', $container);

        if (isset($container->privates['.service_locator.wUUQci5.App\\Controller\\TransportController::deleteTransport()'])) {
            return $container->privates['.service_locator.wUUQci5.App\\Controller\\TransportController::deleteTransport()'];
        }

        return $container->privates['.service_locator.wUUQci5.App\\Controller\\TransportController::deleteTransport()'] = $instance;
    }
}
