<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportControllertransportsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SkzdxpB.App\Controller\TransportController::transports()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SkzdxpB.App\\Controller\\TransportController::transports()'] = ($container->privates['.service_locator.SkzdxpB'] ?? $container->load('get_ServiceLocator_SkzdxpBService'))->withContext('App\\Controller\\TransportController::transports()', $container);
    }
}
