<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWheelSpinRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\WheelSpinRepository' shared autowired service.
     *
     * @return \App\Repository\WheelSpinRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'WheelSpinRepository.php';

        return $container->privates['App\\Repository\\WheelSpinRepository'] = new \App\Repository\WheelSpinRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
