<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWheelControllerspinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fwU_nj3.App\Controller\WheelController::spin()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wheelRepo' => ['privates', 'App\\Repository\\WheelSpinRepository', 'getWheelSpinRepositoryService', true],
            'sessionRepo' => ['privates', 'App\\Repository\\QuizSessionRepository', 'getQuizSessionRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'wheelRepo' => 'App\\Repository\\WheelSpinRepository',
            'sessionRepo' => 'App\\Repository\\QuizSessionRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\WheelController::spin()', $container);

        if (isset($container->privates['.service_locator.fwU_nj3.App\\Controller\\WheelController::spin()'])) {
            return $container->privates['.service_locator.fwU_nj3.App\\Controller\\WheelController::spin()'];
        }

        return $container->privates['.service_locator.fwU_nj3.App\\Controller\\WheelController::spin()'] = $instance;
    }
}
