<?php

namespace ContainerOiU8tml;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWhatsAppControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\WhatsAppController' shared autowired service.
     *
     * @return \App\Controller\WhatsAppController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'WhatsAppController.php';

        $container->services['App\\Controller\\WhatsAppController'] = $instance = new \App\Controller\WhatsAppController(($container->privates['App\\Service\\WhatsAppService'] ?? $container->load('getWhatsAppServiceService')), $container->getEnv('GEMINI_API_KEY'));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\WhatsAppController', $container));

        return $instance;
    }
}
