<?php

namespace ContainerYpa7J3a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_CompressorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'asset_mapper.compressor' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Compressor\ChainCompressor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'asset-mapper'.\DIRECTORY_SEPARATOR.'Compressor'.\DIRECTORY_SEPARATOR.'CompressorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'asset-mapper'.\DIRECTORY_SEPARATOR.'Compressor'.\DIRECTORY_SEPARATOR.'ChainCompressor.php';

        return $container->privates['asset_mapper.compressor'] = new \Symfony\Component\AssetMapper\Compressor\ChainCompressor(NULL, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
