<?php

namespace ContainerYpa7J3a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAssetMapper_Assets_Command_CompressService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'asset_mapper.assets.command.compress' shared service.
     *
     * @return \Symfony\Component\AssetMapper\Command\CompressAssetsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'asset-mapper'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'CompressAssetsCommand.php';

        $container->privates['asset_mapper.assets.command.compress'] = $instance = new \Symfony\Component\AssetMapper\Command\CompressAssetsCommand(($container->privates['asset_mapper.compressor'] ?? $container->load('getAssetMapper_CompressorService')));

        $instance->setName('assets:compress');
        $instance->setDescription('Pre-compresses files to serve through a web server');

        return $instance;
    }
}
