<?php

namespace ContainerYpa7J3a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoriteRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\FavoriteRepository' shared autowired service.
     *
     * @return \App\Repository\FavoriteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'FavoriteRepository.php';

        return $container->privates['App\\Repository\\FavoriteRepository'] = new \App\Repository\FavoriteRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
