<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYpa7J3a\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYpa7J3a/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerYpa7J3a.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerYpa7J3a\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerYpa7J3a\App_KernelTestDebugContainer([
    'container.build_hash' => 'Ypa7J3a',
    'container.build_id' => '2b9e7736',
    'container.build_time' => 1778025460,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYpa7J3a');
