<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkCg2TL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkCg2TL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOkCg2TL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOkCg2TL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOkCg2TL\App_KernelDevDebugContainer([
    'container.build_hash' => 'OkCg2TL',
    'container.build_id' => 'f20f1c4a',
    'container.build_time' => 1778799692,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkCg2TL');
